spring:
  datasource:
    name: mydb
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.1.120:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  dubbo:
    application:
      name: apartment_provider
      timeout: 3000
    registry:
      address: zookeeper://127.0.0.1:2181
    protocol:
      name: dubbo
      port: 20880
    scan: com.jk.service
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123
    jedis:
      pool:
        max-active: 100
        max-idle: 10

  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
mybatis:
    mapperLocations: classpath*:mybatis/mapper-*.xml
    typeAliasesPackage: com.jk.model
server:
   port: 8081
